/**
 * ============================================================================
 * DEVELOPMENT ONLY — NOT REAL MEDICAL OUTPUT
 * ============================================================================
 * 
 * DISCLAIMER:
 * The data structures below are placeholder mock objects exclusively provided
 * for UI layout demonstration, testing, and SIH 2026 presentation previews.
 * 
 * The real screening output and heatmaps will be generated by the separate
 * MATLAB AI pipeline (ResNet-18 + Grad-CAM) once connected via the backend API.
 * 
 * Do NOT use these values for clinical diagnosis or medical decision making.
 * ============================================================================
 */

import type { ScreeningResult } from '../types/screening';

// High-fidelity SVG mock of a retinal fundus image (Normal / Mild / Severe)
export const createMockFundusImage = (type: 'normal' | 'moderate_dr' | 'severe_dr'): string => {
  const isSevere = type === 'severe_dr';
  const isModerate = type === 'moderate_dr';
  
  // High quality SVG representation of fundus with macula, optic disc, blood vessels & microaneurysms
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 600" width="600" height="600">
    <defs>
      <radialGradient id="fundusGrad" cx="50%" cy="50%" r="50%">
        <stop offset="0%" stop-color="#b93815" />
        <stop offset="60%" stop-color="#8a1c0b" />
        <stop offset="90%" stop-color="#550c05" />
        <stop offset="100%" stop-color="#240401" />
      </radialGradient>
      <radialGradient id="opticDisc" cx="45%" cy="45%" r="50%">
        <stop offset="0%" stop-color="#fef08a" />
        <stop offset="70%" stop-color="#fbbf24" />
        <stop offset="100%" stop-color="#d97706" />
      </radialGradient>
      <radialGradient id="macula" cx="50%" cy="50%" r="50%">
        <stop offset="0%" stop-color="#450a0a" stop-opacity="0.8" />
        <stop offset="100%" stop-color="#7f1d1d" stop-opacity="0.1" />
      </radialGradient>
      <filter id="blurFilter" x="-20%" y="-20%" width="140%" height="140%">
        <feGaussianBlur stdDeviation="3" />
      </filter>
    </defs>

    <!-- Retina Background Circle -->
    <circle cx="300" cy="300" r="285" fill="url(#fundusGrad)" stroke="#1e293b" stroke-width="4" />

    <!-- Optic Disc (Nasal side) -->
    <ellipse cx="200" cy="300" rx="38" ry="46" fill="url(#opticDisc)" opacity="0.95" />
    <ellipse cx="200" cy="300" rx="20" ry="24" fill="#fef9c3" opacity="0.7" />

    <!-- Macula / Fovea (Temporal side) -->
    <circle cx="380" cy="310" r="32" fill="url(#macula)" />
    <circle cx="380" cy="310" r="4" fill="#260402" opacity="0.9" />

    <!-- Retinal Vascular Tree (Superior & Inferior Arcades) -->
    <g stroke="#600906" stroke-linecap="round" fill="none" opacity="0.85">
      <!-- Upper Temporal Arcade -->
      <path d="M 200 280 C 215 220, 260 170, 360 170 C 430 170, 480 210, 520 270" stroke-width="6.5" />
      <path d="M 280 190 Q 330 140 400 135" stroke-width="3.5" />
      <path d="M 370 170 Q 420 185 460 210" stroke-width="3" />
      
      <!-- Lower Temporal Arcade -->
      <path d="M 200 320 C 220 380, 270 430, 370 430 C 440 430, 490 390, 530 330" stroke-width="6.5" />
      <path d="M 290 410 Q 340 460 410 465" stroke-width="3.5" />
      <path d="M 380 430 Q 430 415 470 390" stroke-width="3" />

      <!-- Nasal Arcades -->
      <path d="M 180 285 C 150 250, 110 240, 60 250" stroke-width="4.5" />
      <path d="M 180 315 C 150 350, 110 360, 60 350" stroke-width="4.5" />
      
      <!-- Fine Venules & Capillaries -->
      <path d="M 330 200 Q 350 240 370 280" stroke-width="2" stroke="#480504" />
      <path d="M 330 400 Q 350 360 370 330" stroke-width="2" stroke="#480504" />
    </g>

    <!-- Pathological Lesions for DR preview -->
    ${(isModerate || isSevere) ? `
      <!-- Microaneurysms (tiny reddish dots) -->
      <g fill="#991b1b" opacity="0.95">
        <circle cx="340" cy="270" r="3.5" />
        <circle cx="355" cy="350" r="4" />
        <circle cx="410" cy="280" r="3" />
        <circle cx="430" cy="320" r="4" />
        <circle cx="320" cy="330" r="3" />
        <circle cx="390" cy="370" r="4.5" />
        <circle cx="450" cy="260" r="3.5" />
      </g>

      <!-- Blot / Flame Hemorrhages -->
      <g fill="#7f1d1d" opacity="0.9">
        <ellipse cx="360" cy="250" rx="9" ry="5" transform="rotate(25 360 250)" />
        <ellipse cx="420" cy="340" rx="11" ry="6" transform="rotate(-30 420 340)" />
        <ellipse cx="310" cy="290" rx="8" ry="4" transform="rotate(45 310 290)" />
        ${isSevere ? `
          <ellipse cx="440" cy="220" rx="14" ry="7" transform="rotate(15 440 220)" />
          <ellipse cx="330" cy="380" rx="16" ry="8" transform="rotate(-20 330 380)" />
          <ellipse cx="470" cy="300" rx="12" ry="6" />
        ` : ''}
      </g>

      <!-- Hard Exudates (Yellowish lipid deposits) -->
      <g fill="#fef08a" opacity="0.85">
        <circle cx="395" cy="265" r="3.5" />
        <circle cx="402" cy="268" r="4.5" />
        <circle cx="409" cy="262" r="3" />
        <circle cx="415" cy="270" r="4" />
        <circle cx="380" cy="360" r="3.5" />
        <circle cx="372" cy="365" r="3" />
      </g>
    ` : ''}

    ${isSevere ? `
      <!-- Cotton Wool Spots (Soft Exudates - Nerve fiber infarcts) -->
      <g fill="#fef3c7" opacity="0.75" filter="url(#blurFilter)">
        <ellipse cx="340" cy="230" rx="16" ry="12" />
        <ellipse cx="450" cy="360" rx="20" ry="14" />
      </g>
    ` : ''}
  </svg>`;

  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
};

import matlabGradCamIntegrated from '../assets/matlab_gradcam_integrated.png';

// Real MATLAB Grad-CAM PNG asset exported from runNetraguardIntegration.m
export const DEMO_SAMPLE_FUNDUS_URL = createMockFundusImage('moderate_dr');
export const DEMO_SAMPLE_GRANCAM_URL = matlabGradCamIntegrated;

export const DEMO_SCREENING_RECORDS: ScreeningResult[] = [
  {
    id: 'SCR-2026-0842',
    patientId: 'PT-KA-9402',
    patientAge: 56,
    patientGender: 'Female',
    centerLocation: 'PHC Doddaballapura, Karnataka',
    timestamp: '2026-09-26T10:14:00Z',
    prediction: 'Moderate Non-Proliferative DR',
    class: 2,
    confidence: 0.924,
    referable: true,
    macularInvolvementSuspected: true,
    recommendation: 'Recommend clinical examination by an ophthalmologist within 4-6 weeks. Monitor HbA1c control.',
    imageQuality: {
      status: 'Adequate',
      focusScore: 0.94,
      illuminationScore: 0.89,
      fieldCoverageScore: 0.95,
      artifactsDetected: false,
      notes: 'Macular center and optic disc clearly resolved; minimal motion artifact.',
    },
    originalImageUrl: createMockFundusImage('moderate_dr'),
    processedImageUrl: createMockFundusImage('moderate_dr'),
    gradCamImageUrl: matlabGradCamIntegrated,
    gradCamAvailable: true,
    gradCamLayer: 'res5b_relu',
    gradCamSource: 'MATLAB Person 4 Grad-CAM Integration Pipeline',
    clinicalStatus: 'Pending Review',
    doctorNotes: '',
  },
  {
    id: 'SCR-2026-0841',
    patientId: 'PT-KA-9388',
    patientAge: 48,
    patientGender: 'Male',
    centerLocation: 'Vision Center Ramanagara, Karnataka',
    timestamp: '2026-09-26T09:45:00Z',
    prediction: 'No Apparent DR',
    class: 0,
    confidence: 0.978,
    referable: false,
    macularInvolvementSuspected: false,
    recommendation: 'Annual retinal screening recommended. Maintain standard glycemic management.',
    imageQuality: {
      status: 'Adequate',
      focusScore: 0.96,
      illuminationScore: 0.93,
      fieldCoverageScore: 0.98,
      artifactsDetected: false,
      notes: 'Excellent image clarity with crisp vascular margins.',
    },
    originalImageUrl: createMockFundusImage('normal'),
    processedImageUrl: createMockFundusImage('normal'),
    gradCamImageUrl: undefined,
    gradCamAvailable: false,
    gradCamError: 'Grad-CAM is unavailable because the MATLAB explainability pipeline is not connected.',
    clinicalStatus: 'Reviewed',
    reviewedBy: 'Dr. Aris Thorne, MD (Ophthal)',
    reviewTimestamp: '2026-09-26T11:00:00Z',
    doctorNotes: 'Confirmed no microvascular abnormalities. Clear optic disc. Patient counselled for annual checkup.',
  },
  {
    id: 'SCR-2026-0839',
    patientId: 'PT-KA-9345',
    patientAge: 62,
    patientGender: 'Male',
    centerLocation: 'CHC Nelamangala, Karnataka',
    timestamp: '2026-09-25T16:20:00Z',
    prediction: 'Severe Non-Proliferative DR',
    class: 3,
    confidence: 0.625,
    referable: true,
    macularInvolvementSuspected: true,
    recommendation: 'Ophthalmologist review recommended within 2 weeks. Comprehensive dilated fundus examination needed.',
    imageQuality: {
      status: 'Adequate',
      focusScore: 0.88,
      illuminationScore: 0.86,
      fieldCoverageScore: 0.92,
      artifactsDetected: false,
      notes: 'Multiple quadrant intraretinal hemorrhages and cotton-wool patches detected.',
    },
    originalImageUrl: createMockFundusImage('severe_dr'),
    processedImageUrl: createMockFundusImage('severe_dr'),
    gradCamImageUrl: matlabGradCamIntegrated,
    gradCamAvailable: true,
    gradCamLayer: 'res5b_relu',
    gradCamSource: 'MATLAB Person 4 Grad-CAM Integration Pipeline',
    clinicalStatus: 'Referred',
    reviewedBy: 'Dr. Priya V. Sharma, MS (Eye)',
    reviewTimestamp: '2026-09-25T17:10:00Z',
    doctorNotes: 'Marked venous beading and extensive blot hemorrhages in superior arcades. Referred to District Hospital Eye OPD.',
  },
  {
    id: 'SCR-2026-0835',
    patientId: 'PT-KA-9290',
    patientAge: 51,
    patientGender: 'Female',
    centerLocation: 'Mobile Van Screening, Tumakuru',
    timestamp: '2026-09-25T14:05:00Z',
    prediction: 'Mild Non-Proliferative DR',
    class: 1,
    confidence: 0.871,
    referable: false,
    macularInvolvementSuspected: false,
    recommendation: 'Repeat screening in 6-12 months. Diabetic lifestyle and blood sugar optimization advised.',
    imageQuality: {
      status: 'Adequate',
      focusScore: 0.91,
      illuminationScore: 0.87,
      fieldCoverageScore: 0.93,
      artifactsDetected: false,
      notes: 'Isolated microaneurysm detected temporal to fovea.',
    },
    originalImageUrl: createMockFundusImage('moderate_dr'),
    processedImageUrl: createMockFundusImage('moderate_dr'),
    gradCamImageUrl: undefined,
    gradCamAvailable: false,
    gradCamError: 'Grad-CAM is unavailable because the MATLAB explainability pipeline is not connected.',
    clinicalStatus: 'Reviewed',
    reviewedBy: 'Dr. Aris Thorne, MD (Ophthal)',
    reviewTimestamp: '2026-09-25T15:00:00Z',
    doctorNotes: 'Minor microaneurysm noted. Glycemic control review recommended.',
  },
  {
    id: 'SCR-2026-0830',
    patientId: 'PT-KA-9211',
    patientAge: 68,
    patientGender: 'Male',
    centerLocation: 'PHC Kolar Rural, Karnataka',
    timestamp: '2026-09-24T11:30:00Z',
    prediction: 'Proliferative DR',
    class: 4,
    confidence: 0.942,
    referable: true,
    macularInvolvementSuspected: true,
    recommendation: 'Immediate tertiary referral. High risk of preretinal hemorrhage and vision loss.',
    imageQuality: {
      status: 'Adequate',
      focusScore: 0.85,
      illuminationScore: 0.82,
      fieldCoverageScore: 0.89,
      artifactsDetected: false,
      notes: 'Neovascularization at disc (NVD) suspected.',
    },
    originalImageUrl: createMockFundusImage('severe_dr'),
    processedImageUrl: createMockFundusImage('severe_dr'),
    gradCamImageUrl: undefined,
    gradCamAvailable: false,
    gradCamError: 'Grad-CAM is unavailable because the MATLAB explainability pipeline is not connected.',
    clinicalStatus: 'Referred',
    reviewedBy: 'Dr. Priya V. Sharma, MS (Eye)',
    reviewTimestamp: '2026-09-24T12:00:00Z',
    doctorNotes: 'Urgent tele-consultation booked with Minto Eye Hospital.',
  },
];
